2018-02-02 13:51:10,849 ERROR: Exception on /user/test [GET] [in /Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/justencracraft/source/python/microblog/app/routes.py", line 73, in user
    return render_template('user.html', user=user, posts=posts)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/justencracraft/source/python/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends 'base.html' %} {% block content %}
  File "/Users/justencracraft/source/python/microblog/app/templates/base.html", line 25, in top-level template code
    {% endif %} {% endwith %} {% block content %}{% endblock %}
  File "/Users/justencracraft/source/python/microblog/app/templates/user.html", line 14, in block "content"
    <p><a href="{{ url_for('follow', username=user.username) }}">Follow</a></p>
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'follow' with values ['username']. Did you mean 'login' instead?
2018-02-02 13:58:09,033 INFO: Microblog startup [in /Users/justencracraft/source/python/microblog/app/__init__.py:42]
2018-02-05 11:46:21,090 INFO: Microblog startup [in /Users/justencracraft/source/python/microblog/app/__init__.py:42]
2018-02-05 11:46:42,441 ERROR: Exception on /index [GET] [in /Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/justencracraft/source/python/microblog/app/routes.py", line 38, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/justencracraft/source/python/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/justencracraft/source/python/microblog/app/templates/base.html", line 25, in top-level template code
    {% endif %} {% endwith %} {% block content %}{% endblock %}
  File "/Users/justencracraft/source/python/microblog/app/templates/index.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "/Users/justencracraft/source/python/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
